baseURL = "https://hongthanh909.github.io/fcj-workshop-template-main/"
relativeURLs = false
canonifyURLs = true

theme = "hugo-theme-learn"

languageCode = "en"
defaultContentLanguageInSubdir = false
defaultContentLanguage = "en"
hasCJKLanguage = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  description = ""
  author = "HongNTSE183239@fpt.edu.vn"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[languages]
  [languages.en]
  title = "Internship Report"
  weight = 1
  languageName = "English"

  [[languages.en.menu.shortcuts]]
  name = "<i class='fab fa-facebook'></i> AWS Study Group"
  identifier = "AWS Study Group FB"
  url = "https://www.facebook.com/groups/awsstudygroupfcj/"
  weight = 20

  [languages.vi]
  title = "Bao cao thuc tap"
  weight = 2
  languageName = "Tieng Viet"

  [[languages.vi.menu.shortcuts]]
  name = "<i class='fab fa-facebook'></i> AWS Study Group"
  identifier = "AWS Study Group FB"
  url = "https://www.facebook.com/groups/awsstudygroupfcj/"
  weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
